version: '3.4'

services:
  hw2nodejs:
    image: hw2nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5678:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "studentserver.js"]
